import {Component} from '@angular/core';

enum Language {
  Python = 'Python',
  JavaScript = 'JavaScript',
  TypeScript = 'TypeScript',
  Shell = 'Shell',
  Java = 'Java',
  Kotlin = 'Kotlin',
  C = 'C',
  Cpp = 'C++',
  GLSL = 'GLSL'
}

export interface Project {
  github?: string;
  name: string;
  description: string;
  link: string;
  languages: Language[];
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  personalProjects: Project[] = [
    {
      github: 'https://github.com/olliechick/scattergories',
      name: 'Scattergories',
      link: 'https://olliechick.co.nz/scattergories',
      description: ': a web version of the board game Scattergories',
      languages: [Language.TypeScript]
    },
    {
      name: 'Codenames',
      link: 'https://olliechick.co.nz/codenames',
      description: ': a web version of the board for the board game Codenames (taken down for copyright reasons)',
      languages: [Language.TypeScript]
    },
    {
      github: 'https://github.com/olliechick/scumgraph',
      name: 'Scum graph',
      link: 'https://play.google.com/store/apps/details?id=nz.co.olliechick.scumgraph',
      description: ': an Android app to track players\' scores throughout the card game Scum using a graph on a Chromecast',
      languages: [Language.Kotlin]
    },
    {
      github: 'https://github.com/olliechick/amp-kiwisaver-helper',
      name: 'AMP KiwiSaver helper',
      link: 'https://olliechick.co.nz/kiwisaver',
      description: ': a web tool to calculate how much you will need to pay to make the most of government contributions based on reports generated by AMP',
      languages: [Language.TypeScript]
    },
    {
      github: 'https://github.com/olliechick/agilefant-timesheet-parser',
      name: 'Agilefant timesheet parser',
      link: '',
      description: ': a script to track hours logged per user on the free version of Agilefant',
      languages: [Language.Python]
    },
    {
      github: 'https://github.com/olliechick/timestamper',
      name: 'timestamper',
      link: '',
      description: ': an FFmpeg wrapper to make it easy to create a video with a ticking timestamp from a still image, an audio file, and a start time',
      languages: [Language.Shell]
    }
  ];

  fourthYearProjects: Project[] = [
    {
      github: 'https://github.com/olliechick/hivo',
      name: 'HiVo',
      link: 'https://play.google.com/store/apps/details?id=nz.co.olliechick.hivo',
      description: ': an Android app that can continuously record audio in the background, ' +
        'then gives you the ability to save a portion of it when something interesting happens; ' +
        'you can also schedule recordings to happen in the future',
      languages: [Language.Kotlin]
    }, {
      github: 'https://github.com/olliechick/morepork',
      name: 'Morepork',
      link: 'https://play.google.com/store/apps/details?id=nz.co.olliechick.morepork',
      description: ': a side-scrolling Android game where you control a morepork, trying to avoid obstacles, created as part of a pair',
      languages: [Language.Kotlin]
    }, {
      github: 'https://github.com/olliechick/unfollowers',
      name: 'Unfollowers',
      link: 'https://play.google.com/store/apps/details?id=me.olliechick.instagramunfollowers',
      description: ': an Android app to track Instagram unfollowers',
      languages: [Language.Kotlin]
    }, {
      github: 'https://github.com/olliechick/exploding-gumbo-and-terrain',
      name: '',
      link: '',
      description: 'An exploding elephant model, and a landscape with adjustable terrain, written using OpenGL 4',
      languages: [Language.Cpp, Language.GLSL]
    }, {
      github: 'https://github.com/olliechick/character-animations',
      name: '',
      link: '',
      description: 'Three animated character models, written using OpenGL 2',
      languages: [Language.Cpp]
    }
  ];

  thirdYearProjects: Project[] = [
    {
      github: 'https://github.com/UCNZ-SENG302-2018-Donaco/OrgaNZ',
      name: 'OrgaNZ',
      link: '',
      description: ': an organ donation management system, which is designed for tabletop touchscreens (but also has a desktop mode), created as part of a team of 8',
      languages: [Language.Java]
    }, {
      github: 'https://github.com/olliechick/auctions-frontend',
      name: 'The frontend of an auction website',
      link: 'http://olliechick.co.nz/auctions',
      description: ', developed using Vue.js',
      languages: [Language.JavaScript]
    }, {
      github: 'https://github.com/olliechick/auctions-backend-deprecated',
      name: 'The backend of an auction website',
      link: '',
      description: ', developed using Node.js with Express (but a backend provided by the lecturer was used when developing the frontend)',
      languages: [Language.JavaScript]
    }, {
      github: 'https://github.com/olliechick/graphics-scene-cosc363',
      name: '',
      link: '',
      description: 'A graphics scene, written using OpenGL2',
      languages: [Language.Cpp]
    }, {
      github: 'https://github.com/olliechick/ray-tracer',
      name: '',
      link: '',
      description: 'A ray tracer, written using OpenGL2',
      languages: [Language.Cpp]
    }
  ];

  secondYearProjects: Project[] = [
    {
      github: 'https://github.com/olliechick/cyc',
      name: 'CYC: Your Cycling',
      link: '',
      description: ': a desktop program for planning cycling routes',
      languages: [Language.Java]
    }, {
      github: 'https://github.com/olliechick/VirtualPetsAssignment',
      name: 'VirtualPets',
      link: '',
      description: ': a turn-based Tamagotchi-like game, created as part of a pair',
      languages: [Language.Java]
    }, {
      github: 'https://github.com/olliechick/ence260-game',
      name: '',
      link: '',
      description: 'A tic-tac-toe game playable on the UC Fun Kit (a microcontroller kit), created as part of a pair',
      languages: [Language.C]
    }, {
      github: 'https://github.com/olliechick/sockets',
      name: 'Sockets',
      link: '',
      description: ': an implementation of the alternating-bit protocol, with a sender, channel emulator, and receiver, created as part of a pair',
      languages: [Language.Python]
    }
  ];

  highSchoolProjects: Project[] = [{
    github: 'https://github.com/olliechick/calculator',
    name: 'GUI calculator',
    link: '',
    description: '',
    languages: [Language.Python]
  }, {
    github: 'https://github.com/olliechick/operation-cranberry',
    name: 'Operation Cranberry',
    link: '',
    description: ': a text-based zombie game',
    languages: [Language.Python]
  }];
}


// , {
//   github: 'https://github.com/olliechick/',
//     name: '',
//     link: '',
//     description: '',
//     languages: [Language.]
// }
