import {Component} from '@angular/core';

enum Language {
  Python = 'Python',
  JavaScript = 'JavaScript',
  TypeScript = 'TypeScript',
  Shell = 'Shell',
  Java = 'Java',
  Kotlin = 'Kotlin',
  C = 'C',
  Cpp = 'C++',
  GLSL = 'GLSL'
}

export interface Project {
  github: string;
  name: string;
  description: string;
  link: string;
  language: Language;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  displayedColumns: string[] = ['description', 'language', 'github'];
  personalProjects: Project[] = [
    {
      github: 'https://github.com/olliechick/codenames',
      name: 'Codenames',
      link: 'https://olliechick.co.nz/codenames',
      description: 'a web version of the board for the board game Codenames',
      language: Language.TypeScript
    },
    {
      github: 'https://github.com/olliechick/scumgraph',
      name: 'Scum graph',
      link: 'https://play.google.com/store/apps/details?id=nz.co.olliechick.scumgraph',
      description: 'an Android app to track players\' scores throughout the card game Scum using a graph on a Chromecast',
      language: Language.Kotlin
    },
    {
      github: 'https://github.com/olliechick/amp-kiwisaver-helper',
      name: 'AMP KiwiSaver helper',
      link: 'https://olliechick.co.nz/kiwisaver',
      description: 'a web tool to calculate how much you will need to pay to make the most of government contributions based on reports generated by AMP',
      language: Language.TypeScript
    },
    {
      github: 'https://github.com/olliechick/agilefant-timesheet-parser',
      name: 'Agilefant timesheet parser',
      link: '',
      description: 'a script to track hours logged per user on the free version of Agilefant',
      language: Language.Python
    },
    {
      github: 'https://github.com/olliechick/timestamper',
      name: 'timestamper',
      link: '',
      description: 'an FFmpeg wrapper to make it easy to create a video with a ticking timestamp from a still image, an audio file, and a start time',
      language: Language.Shell
    }
  ];

  fourthYearProjects: Project[] = [
    {
      github: 'https://github.com/olliechick/',
      name: '',
      link: 'https://olliechick.co.nz/',
      description: '',
      language: null
    }
  ];
}
